stages:
#- build
  - test
#- deploy
#- review
#- dast
#- staging
#- canary
#- production
#- incremental rollout 10%
#- incremental rollout 25%
#- incremental rollout 50%
#- incremental rollout 100%
#- performance
#- cleanup

variables:
  GLOBAL_VAR: "A global variable"

test-job:
  variables:
    JOB_VAR: "A job variable"
  tags:
    - backend
  script:
    - echo "The job's stage is '$CI_JOB_STAGE'"
    - echo "Variables are '$GLOBAL_VAR' and '$JOB_VAR'"

test-job2:
  stage: test
  tags:
    - backend
  script:
    - echo "Variables are '$GLOBAL_VAR' and '$JOB_VAR'"

