stages:
  - pre-build
#- build
  - test
  - deploy
#- review
#- dast
#- staging
#- canary
#- production
#- incremental rollout 10%
#- incremental rollout 25%
#- incremental rollout 50%
#- incremental rollout 100%
#- performance
#- cleanup

variables:
  GOLANGCI_LINT_VERSION: "v1.64.8"

# プレビルド：常に実行
pre-build-job:
  stage: pre-build
  image: golang:1.24.4-alpine
  before_script:
    - go install github.com/google/wire/cmd/wire@latest
  script:
    - wire ./di || true
  artifacts:
    paths:
      - di/wire_gen.go
  rules:
    - when: always  # 常に実行

# Lint：develop, staging, main 以外
lint-job:
  stage: test
  image: golangci/golangci-lint:${GOLANGCI_LINT_VERSION}
  script:
    - echo "Running revive lint check..."
    - golangci-lint --version
    - export PATH=$PATH:/go/bin
    - golangci-lint run --config .golangci.yml --out-format junit-xml ./... > lint-report.xml
  artifacts:
    when: always
    reports:
      junit: lint-report.xml
    paths:
      - lint-report.xml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_COMMIT_BRANCH != "staging" && $CI_COMMIT_BRANCH != "main"'
      when: always

# Unit Test：develop, staging, main 以外
unit-test-job:
  stage: test
  image: golang:1.24.4-alpine
  before_script:
    - go install gotest.tools/gotestsum@latest
    - go install github.com/t-yuki/gocover-cobertura@latest
  script:
    - go mod tidy
    - gotestsum --junitfile unit-test-report.xml -- -coverprofile=coverage.out ./...
    - gocover-cobertura < coverage.out > coverage.xml
  artifacts:
    reports:
      junit: unit-test-report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.out
      - coverage.html
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_COMMIT_BRANCH != "staging" && $CI_COMMIT_BRANCH != "main"'
      when: always

# 共通デプロイジョブ：develop/staging/main用
deploy-job:
  stage: deploy
  script:
    - echo "Deploying branch - $CI_COMMIT_BRANCH"
#    - echo "Target Host - $DEPLOY_TARGET"
#    - echo "Using ENV - $APP_ENV"
#    - ssh user@$DEPLOY_TARGET "deploy-command --env=$APP_ENV"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
#      variables:
#        DEPLOY_TARGET: $DEV_DEPLOY_TARGET
#        APP_ENV: $DEV_APP_ENV
      when: always
    - if: '$CI_COMMIT_BRANCH == "staging"'
#      variables:
#        DEPLOY_TARGET: $STG_DEPLOY_TARGET
#        APP_ENV: $STG_APP_ENV
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
#      variables:
#        DEPLOY_TARGET: $PRD_DEPLOY_TARGET
#        APP_ENV: $PRD_APP_ENV
      when: always
  dependencies:
    - pre-build-job
